version: '3.2'
services:
  server:
    image: node:lts-slim
    depends_on:
      - client
    volumes:
      - ./api:/src
    working_dir: /src
    command: ['npm', 'start']
    ports:
      - "3001:3001"

  client:
    image: node:lts-slim
    volumes:
      - ./client:/src
    working_dir: /src
    command: ['npm', 'start', 'sleep 10']
    ports:
      - "3000:3000"

