version: '3'
services:
  server:
    image: node:lts-slim
    volumes:
      - ./api:/src
    working_dir: /src
    command: ['npm', 'start']
    ports:
      - 3001:3001
  client:
    image: node:lts-slim
    volumes:
      - ./client:/src
    working_dir: /src
    command: ['npm', 'start']
    ports:
      - 3000:3000
