name: Run Test Suites
on: [push]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run:
          cd api && npm install
        name: 'Install API dependencies'
      - run:
          cd client && npm install
        name: 'Install Client dependencies'
      - run:
          cd api-tests && npm install
        name: 'Install Load tests dependencies'
      - run:
          cd api && npm start &
        name: 'Start API'
      - run:
          cd api-tests && npm run wait:server && npm test
        name: 'Run API tests'
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: api-tests/reports

  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run:
          cd api && npm install
        name: 'Installing API dependencies'
      - run:
          cd client && npm install
        name: 'Installing Client dependencies'
      - run:
          cd api && npm start &
        name: 'start api'
      - run:
          cd client && npm start &
        name: 'start app'
      - run:
          npm install
        name: 'Installing cypress dependencies'
      - uses: cypress-io/github-action@v2
        with:
          install: false
          wait-on: 'http://localhost:3000'
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-test-results
          path: cypress/reports/index.html

  run-load-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run:
          cd api && npm install
        name: 'Install API dependencies'
      - run:
          cd load-tests && npm install
        name: 'Install Load tests dependencies'
      - run:
          cd api && npm start &
        name: 'Start API'
      - run: |
          cd load-tests && npm run wait:server && npm test
        name: 'Run Load tests'
